# Generated by Django 3.0.1 on 2020-01-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.CharField(max_length=15)),
                ('status_up', models.BooleanField()),
                ('last_update', models.DateTimeField(verbose_name='last_update')),
                ('creation_date', models.DateTimeField(verbose_name='creation_date')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=15)),
                ('protocol', models.CharField(max_length=5)),
                ('port_number', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
                ('comment', models.CharField(max_length=1000)),
                ('last_update', models.DateTimeField(verbose_name='last_update')),
                ('creation_date', models.DateTimeField(verbose_name='creation_date')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmap_app.Server')),
            ],
        ),
    ]
